blog_page:
    path:     /page/{page}
    defaults: { _controller: BlogBundle:Article:page, page: 1 }
    requirements:
      pageNumber: \d+

blog_article:
    path:     /article/{id}
    defaults: { _controller: BlogBundle:Article:article, id: 1 }
    requirements:
      id: \d+
