blog_index:
  path: /
  defaults: { _controller: BlogBundle:Article:page, page: 1 }


blog_page:
    path:     /page/{page}
    defaults: { _controller: BlogBundle:Article:page, page: 1 }
    requirements:
      pageNumber: \d+

blog_article:
    path:     /article/{id}
    defaults: { _controller: BlogBundle:Article:article, id: 1 }
    requirements:
      id: \d+

edit_article:
    path: /edit_article/{id}
    defaults: {_controller: BlogBundle:EditArticle:edit }
    requirements:
      id: \d+

delete_article:
    path: /delete_article/{id}
    defaults: {_controller: BlogBundle:EditArticle:delete }

create_article:
    path: /create_article
    defaults: {_controller: BlogBundle:CreateArticle:create}

manage_article:
    path: /manage_article
    defaults: {_controller: BlogBundle:ManageArticle:manage}

