blog_page:
    path:     /page/{pageNumber}
    defaults: { _controller: BlogBundle:Article:page, pageNumber: 1 }
    requirements:
      pageNumber: \d+

blog_article:
    path:     /article/{id}
    defaults: { _controller: BlogBundle:Article:article, id: 1 }
    requirements:
      id: \d+
